#!/bin/bash
curl --form username=ttt --form password=tttr velox.pw:8000/register
curl --user ttt:tttr --form Name=Ebeoo-raud --form UUID=fda50693-a4e2-4fb1-afcf-c6eb07647825 --form Major=10006 --form Minor=48406 velox.pw:8000/v1/beacons
curl --user ttt:tttr --form Name=Ebeoo-gul --form UUID=fda50693-a4e2-4fb1-afcf-c6eb07647825 --form Major=10005 --form Minor=48406 velox.pw:8000/v1/beacons
curl --user ttt:tttr --form Name=Ebeoo-blaa --form UUID=fda50693-a4e2-4fb1-afcf-c6eb07647825 --form Major=100010 --form Minor=48406 velox.pw:8000/v1/beacons
curl --user ttt:tttr --form Name=NumerosUnos velox.pw:8000/v1/group
curl --user ttt:tttr -d kek velox.pw:8000/v1/group/1/beacon/1
